from typing import List, Dict, Any
from sqlalchemy.orm import Session
from app.models import HistoricalTweet, Tweet, InstagramPost, TweetEdit
from app.services.twitter_client import get_twitter_client
from app.services.tweet_analyzer import TweetAnalyzer
from app.services.claude_client import get_claude_client
from app.services.chatgpt_client import get_chatgpt_client
from datetime import datetime
from zoneinfo import ZoneInfo

# Configure timezone to Central Time (USA)
CENTRAL_TZ = ZoneInfo("America/Chicago")


class ContentGenerator:
    """Main service for generating social media content"""

    def __init__(self, db: Session):
        self.db = db
        self.twitter_client = get_twitter_client()
        self.claude_client = get_claude_client()
        self.chatgpt_client = get_chatgpt_client()

    def fetch_and_store_historical_tweets(self, username: str = "joinferta", count: int = 100) -> int:
        """
        Fetch historical tweets and store in database

        Args:
            username: Twitter username to fetch from
            count: Number of tweets to fetch

        Returns:
            Number of new tweets stored
        """
        # Fetch tweets from Twitter
        tweets = self.twitter_client.fetch_user_tweets(username, max_results=count)

        stored_count = 0
        for tweet_data in tweets:
            # Check if tweet already exists
            existing = self.db.query(HistoricalTweet).filter(
                HistoricalTweet.tweet_id == tweet_data['tweet_id']
            ).first()

            if not existing:
                # Create new historical tweet record
                historical_tweet = HistoricalTweet(
                    tweet_id=tweet_data['tweet_id'],
                    content=tweet_data['content'],
                    posted_date=tweet_data['posted_date'],
                    engagement_metrics=tweet_data['engagement_metrics'],
                    topic_tags=[]  # Will be populated by analyzer
                )
                self.db.add(historical_tweet)
                stored_count += 1

        self.db.commit()
        return stored_count

    def generate_daily_tweets(self, count: int = 25) -> Dict[str, int]:
        """
        Generate daily tweet ideas using both Claude and ChatGPT

        Args:
            count: Total number of tweets to generate (split between AIs)

        Returns:
            Dictionary with counts of tweets generated by each AI
        """
        # Get historical tweets for context
        historical_tweets = self.db.query(HistoricalTweet).all()

        if historical_tweets:
            # Analyze historical tweets if available
            historical_data = [
                {
                    'content': ht.content,
                    'engagement_metrics': ht.engagement_metrics
                }
                for ht in historical_tweets
            ]

            analyzer = TweetAnalyzer(historical_data)
            analysis = analyzer.get_analysis_summary()

            brand_voice_examples = analysis['brand_voice_examples']
            topics = analysis['top_topics']
            common_phrases = analysis['common_phrases']
        else:
            # Use default Ferta brand voice if no historical tweets
            brand_voice_examples = [
                "Natural fertility restoration empowers your body to heal from within. Your journey to parenthood doesn't have to start with IVF.",
                "Did you know? Addressing root causes of infertility through holistic approaches can yield better long-term results than conventional treatments.",
                "Your hormones are messengers. When we listen to what they're telling us through holistic fertility education, real healing begins.",
                "IVF success rates hover around 30-35%. But what if we focused on why your body isn't conceiving naturally first?",
                "Nutrition, stress management, and lifestyle changes aren't just 'nice to have' - they're fundamental to fertility restoration."
            ]
            topics = ['fertility', 'natural', 'holistic', 'health', 'ivf', 'treatment', 'nutrition', 'hormones', 'wellness']
            common_phrases = ['natural fertility', 'holistic approach', 'root cause', 'fertility restoration', 'conventional treatment']

        # Get edit history to learn from user preferences
        edit_examples = []
        tweet_edits = self.db.query(TweetEdit).order_by(TweetEdit.edit_timestamp.desc()).limit(10).all()
        if tweet_edits:
            for edit in tweet_edits:
                edit_examples.append({
                    'original': edit.original_text,
                    'improved': edit.edited_text
                })
            print(f"Using {len(edit_examples)} edit examples to improve tweet generation")

        # For now, use only ChatGPT since Claude model access may be limited
        # Generate all tweets with ChatGPT
        chatgpt_tweets = self.chatgpt_client.generate_tweets(
            count=count,
            brand_voice_examples=brand_voice_examples,
            topics=topics,
            common_phrases=common_phrases,
            edit_examples=edit_examples
        )

        # Store generated tweets in database
        for tweet_text in chatgpt_tweets:
            tweet = Tweet(
                content=tweet_text,
                ai_source='chatgpt',
                status='pending'
            )
            self.db.add(tweet)

        self.db.commit()

        return {
            'claude': 0,
            'chatgpt': len(chatgpt_tweets),
            'total': len(chatgpt_tweets)
        }

    def create_instagram_post_from_tweet(
        self,
        tweet_id: int,
        ai_source: str = 'claude'
    ) -> InstagramPost:
        """
        Convert a tweet into an Instagram post with image

        Args:
            tweet_id: ID of the tweet to convert
            ai_source: Which AI to use ('claude' or 'chatgpt')

        Returns:
            Created InstagramPost object
        """
        # Get the tweet
        tweet = self.db.query(Tweet).filter(Tweet.id == tweet_id).first()
        if not tweet:
            raise ValueError(f"Tweet {tweet_id} not found")

        # Expand into Instagram caption
        if ai_source == 'claude':
            caption = self.claude_client.expand_caption(tweet.content)
        else:
            caption = self.chatgpt_client.expand_caption(tweet.content)

        # Generate image (using ChatGPT/DALL-E as it has image generation)
        image_url = self.chatgpt_client.generate_image(
            prompt="Holistic fertility and wellness theme",
            tweet_text=tweet.content
        )

        # Create Instagram post record
        instagram_post = InstagramPost(
            source_tweet_id=tweet.id,
            caption=caption,
            image_url=image_url,
            status='pending'
        )

        self.db.add(instagram_post)
        self.db.commit()
        self.db.refresh(instagram_post)

        return instagram_post

    def post_tweet(self, tweet_id: int) -> bool:
        """
        Post a tweet to Twitter

        Args:
            tweet_id: ID of the tweet to post

        Returns:
            True if successful
        """
        tweet = self.db.query(Tweet).filter(Tweet.id == tweet_id).first()
        if not tweet:
            raise ValueError(f"Tweet {tweet_id} not found")

        if tweet.status == 'posted':
            raise ValueError("Tweet has already been posted")

        try:
            # Post to Twitter
            twitter_id = self.twitter_client.post_tweet(tweet.content)

            # Update tweet record (use Central Time)
            tweet.twitter_id = twitter_id
            tweet.status = 'posted'
            tweet.posted_time = datetime.now(CENTRAL_TZ)

            self.db.commit()
            return True

        except Exception as e:
            tweet.status = 'failed'
            self.db.commit()
            raise


def get_content_generator(db: Session) -> ContentGenerator:
    """Get content generator instance"""
    return ContentGenerator(db)
